apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  LOG_LEVEL: {{ .Values.configMaps.logLevel | quote }}
  PERSISTENCE: {{ .Values.configMaps.persistence | quote }}
