{{ .Values.service.port }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 80 }}
      targetPort: 3000
