configMaps:
  logLevel: info
  persistence: true

service:
  port: ""

deployment:
  replicaset: 3

cronJob:
  schedule: "0 0 * * *"

ingress:
  ingressClassName: nginx
  rules:
    host: "crm-demo.ddns.net"

